### ISSUE TITLE
Gcps to point work for external positioning but not internal when warping/ transforming

### ISSUE THREAD

**Issue by DLParkin** [azavea/loam#111]
Firstly many thanks for loam, I have been playing around with it for the past fer months and enjoying using it. 

Having an issue which I am unsure if loam or my lack of knowledge with gdal but from what I have read on gdal warping and transform it should be working. 

When i apply commands and send it through loam it outputs a tiff but the gcps seem to only apply to the external bounds where I have adjusted points internally but no changes occur. 

This is the core function that I am using which works for the outer gcps but does not work when trying to change internal points and gcps. 

```loam.open(file).then((ds: any) => {
        ds.convert(stringifyGCP(gcpsArray))
          .then((dsGCP: any) => {
            return dsGCP
              .warp(warpArgs)
              .then((dsWarped: any) => {
                return Promise.all([
                  dsWarped.convert(["-of", "GTiff", "-co", "COMPRESS=JPEG"]), //'-co', 'PHOTOMETRIC=YCBCR', '-co', 'TILED=YES'
                  dsWarped.convert(["-of", "PNG", "-co", "COMPRESS=JPEG"]),
                ])
                  .then(([datasetGTiff, datasetPNG]) => {
                    return Promise.all([
                      datasetGTiff.bytes(),
                      datasetPNG.bytes(),
                    ])
                      .then(([gtiffBytes, pngBytes]) => {
                        const warpedGtiffBlob = new Blob([gtiffBytes]);
                        const warpedPngBlob = new Blob([pngBytes]);
```
 
the example below is a small image but same results when trying with a large image are the same
            
example gcps - 
```-gcp 0.00 0.00 6.082858443260194 50.776186145801745
-gcp 432.00 0.00 6.085175871849061 50.776186145801745
-gcp 432.00 357.00 6.085175871849061 50.77497511582229
-gcp 0.00 357.00 6.082858443260194 50.77497511582229
-gcp 209.20 113.00 6.083984973205042 50.77584862099022
-gcp 293.36 170.00 6.084666347114017 50.77561794936608
-gcp  227.44 234.00 6.08403323354001 50.77528550884761
-gcp 149.33 187.00 6.083367946409385 50.775560281282274```

the warp arguments 

`-rnear-order2-s_srsEPSG:4326-dstnodata-999-t_srsEPSG:3857-overwrite`

any thoughts, links to read or assistance would be appreciated as it is so close to working correctly

Many thanks

**Comment by ddohler** [comment]
Hi @DLParkin -- thanks for the writeup! I have used GCPs with Loam once and did something similar to what you have here: calling `convert()` to add the GCPs and then calling `warp()` to apply them. However, for that work we only used GCPs around the boundary of the image rather than within the bounds.

I see a few small differences between what we did and what you have here that might be worth trying if they're acceptable for your use case:
- We used the `-tps` flag rather than `-order`.
- `-overwrite` shouldn't be necessary; internally, Loam creates a brand new dataset for each stage in the processing, which is essentially the same thing as the `-overwrite` flag, so it should be superfluous (though if you get different results with `-overwrite` and without I would love to hear about it).

One question I also have is whether you've copied the command-line arguments as they're being passed to `convert()` and `warp()` into calls to `gdal_translate` and `gdalwarp` on the command line? That is the easiest way to double-check whether you're using GDAL correctly. Though it's best to use GDAL 2.4 if you can because Loam hasn't been updated to GDAL 3.0 yet (I'm working on it, but GDAL 3+ made major changes to the build system so it hasn't been a straightforward upgrade). If you've done this and it works, but in Loam it doesn't, then that's a key piece of the puzzle.

I hope that's enough info to help you diagnose -- please let me know what you find and whether there's anything else I can do to help!

One other note (not really related to any of the above) is that you can reduce the amount of indentation due to the promises by returning promises at each stage. You're already returning the promises so you should be able to pull the `.then()` calls up to the top level at each stage, like this:

```javascript
ds.convert(stringifyGCP(gcpsArray))
          .then((dsGCP: any) => dsGCP.warp(warpArgs))
          .then((dsWarped: any) => Promise.all([...]))
          .then(...)
          etc.
```

**Comment by DLParkin** [comment]
@ddohler you have no idea how excited I am, thankyou so much! The amount of time I have spent to.... 

Using `-tps` instantly fixed it and now works as expected.

Removing `-overwrite` works just fine 

The result is an in browser image to map editor

![image](https://user-images.githubusercontent.com/22126206/204580447-ad1e02c7-fc6b-4e63-b485-3e9d68f01194.png)

As for the promises yes it was sub par, originally I had it similar but had issues with the error which became messy so many thanks for pointing that out as always wanting to improve. 

Onto the next step of trying to apply colors with `webgl`     

You are my new hero!
